# storage dir
CACHE_DIR = "cache"
DATA_DIR = "data"

# urls for websocket connection
URL = "wss://data.tradingview.com/socket.io/websocket"
PRO_URL = "wss://prodata.tradingview.com/socket.io/websocket"
ORIGIN = "https://www.tradingview.com"
HEADER = {
    "Host": "data.tradingview.com",
    "Connection": "Upgrade",
    "Pragma": "no-cache",
    "Cache-Control": "no-cache",
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    "Upgrade": "websocket",
    "Origin": "https://www.tradingview.com",
    # "Sec-WebSocket-Version": "13", # Breaks when used in websockets.client
    "Accept-Encoding": "gzip, deflate, br",
    "Accept-Language": "en-US,en;q=0.9",
    # "Sec-WebSocket-Key": "pdcnwdPnb+1Zinv7O/nPJA==", # This is the key that is generated by the browser
    "Sec-WebSocket-Extensions": "permessage-deflate; client_max_window_bits",
}  # Only origin is required but we'll add the rest for safety

RESPONSE_TYPE = {
    "qsd": {},
    "quote_completed": {},
    "series_loading": {},
    "symbol_resolved": {},
    "timescale_update": {},
    "series_completed": {},
    "du": {},
    "series_timeframe": {},
    "study_loading": {},
    "study_completed": {},
    "critical_error": {
        "type": "error",
    },
    "protocol_error": {
        "type": "error",
    },
    "series_error": {
        "type": "error",
    },
    "symbol_error": {
        "type": "error",
    },
    "unsupported_resolution": {
        "type": "error",
    },
}
